package Selenium;// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class ExampleTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void example() throws IOException {
    driver.get("https://www.amazon.com/Software-Test-Automation-Mark-Fewster/dp/0201331403/ref=sr_1_6?crid=2DRM9M0WAU6B5&keywords=automation+tools&qid=1638191202&sprefix=automation+tools%2Caps%2C761&sr=8-6");
    driver.manage().window().setSize(new Dimension(1050, 660));
    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
    List<WebElement> reviews = driver.findElements(By.xpath("//div[@class='a-expander-collapsed-height a-row a-expander-container a-expander-partial-collapse-container']"));
    List<String> list = new ArrayList<>();
//    List<WebElement> stars = driver.findElements(By.xpath("//div[@class='a-row']"));
    List<WebElement> stars = driver.findElements(By.cssSelector("a[data-hook='review-star-rating']"));
    List<String> starlist = new ArrayList<>();
    for (WebElement webElement : reviews) {
      String review = webElement.getText();
      System.out.println(review);
      list.add(review);
    }
    for (WebElement webElement : stars){
      String star = webElement.getText();
      System.out.println(star);
      starlist.add(star);
    }
    FileWriter writer = new FileWriter("output12.txt");
    for(String str: list) {
      writer.write(str + System.lineSeparator() + System.lineSeparator());
    }
    writer.close();

    FileWriter writer2 = new FileWriter("output13.txt");
    for(String str: starlist) {
      writer2.write(str + System.lineSeparator() + System.lineSeparator());
    }
    writer.close();


  }
}
