package Selenium;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import io.github.bonigarcia.wdm.WebDriverManager;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class HubSpotNextPageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void hubSpotNextPage() {
    driver.get("https://ecosystem.hubspot.com/marketplace/apps/sales/sales-enablement/office365");
    driver.manage().window().setSize(new Dimension(1536, 824));
    driver.findElement(By.linkText("Reviews")).click();
    driver.findElement(By.cssSelector(".private-paginator__forward-controls > .uiButton")).click();
    driver.findElement(By.cssSelector(".private-paginator__button > i18n-string:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".private-paginator__button > i18n-string:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".private-paginator__button > i18n-string:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
}
