package Selenium;// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.interactions.Actions;

import java.io.FileWriter;
import java.io.IOException;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class TwitterReview {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void example() throws IOException {

        Actions actions = new Actions(driver);

    String URL = "https://twitter.com/search?q=youtube&src=typed_query&f=live";
    String URL1 = "https://twitter.com/search?q=hsbc%20mobile%20banking&src=typed_query&f=live";

        driver.get(URL1);
                driver.manage().window().maximize();
                driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
                JavascriptExecutor js = (JavascriptExecutor) driver;
                List<String> list = new ArrayList<>();
        StringBuilder fileContent = new StringBuilder();
        int i = 0;
        while (i < 3) {
            if(list.size()==60){
                break;
            }
        String reviewId, reviewIdXPath, reviewComment, tweetID, tweetTextIDXPath;
//        js.executeScript("window.scrollTo(0, document.body.scrollHeight)");
//            List<WebElement> reviews = driver.findElements(By.xpath("//article[@data-testid='tweet']"));
//
        List<WebElement> reviews = driver.findElements(By.xpath("//*[@data-testid='tweet']"));
        List<WebElement> tweetBodyPath = driver.findElements(By.xpath("//*[@class = 'css-901oao r-18jsvk2 r-37j5jr r-a023e6 r-16dba41 r-rjixqe r-bcqeeo r-bnwqim r-qvutc0']"));
        for (int j = 1; j < reviews.size(); j++) {

        reviewId = reviews.get(j).getAttribute("aria-labelledby");
        tweetID = tweetBodyPath.get(j).getAttribute("id");
        reviewIdXPath = "//article[@data-testid=\"tweet\" and @aria-labelledby='"+reviewId+"']";


      //  reviewComment=driver.findElement(By.xpath(reviewIdXPath + "//div[@lang=\"en\" and @id='"+tweetID+"']" )).getText(); //+"//div[@id=\"id__oypwvdnz1y\"]"
        //*[@id="id__kn5i726qqja"]
        String review = reviews.get(j).getText().replaceAll("@HSBC_UK", "");;
        System.out.println(review);
        list.add(review);
            System.out.println(list.size());

        try {
        Thread.sleep(1000);
        } catch (Exception e) {
        }

        }
            js.executeScript("window.scrollBy(0,document.body.scrollHeight)");
        try{
        Thread.sleep(1000);
        }
        catch(Exception e) {
        }
        i++;
        }
        FileWriter writer = new FileWriter("twitterRaw.txt");
        for (String str : list) {
        writer.write(str + System.lineSeparator() + System.lineSeparator() + System.lineSeparator());
        }
        writer.close();




        }
    }



//    String URL = "https://twitter.com/search?q=youtube&src=typed_query&f=live";
//    String URL1 = "https://twitter.com/search?q=hsbc%20mobile%20banking&src=typed_query&f=live";
//
//        driver.get(URL1);
//                driver.manage().window().maximize();
//                driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
//                JavascriptExecutor js = (JavascriptExecutor) driver;
//                List<String> list = new ArrayList<>();
//        StringBuilder fileContent = new StringBuilder();
//        int i = 0;
//        while (i < 20) {
//        String reviewId, reviewIdXPath, reviewComment, tweetID, tweetTextIDXPath;
//        js.executeScript("window.scrollTo(0, document.body.scrollHeight)");
////            List<WebElement> reviews = driver.findElements(By.xpath("//article[@data-testid='tweet']"));
////
//        List<WebElement> reviews = driver.findElements(By.xpath("//*[@data-testid='tweet']"));
//        List<WebElement> tweetBodyPath = driver.findElements(By.xpath("//*[@class = 'css-1dbjc4n']"));
//        for (int j = 1; j < reviews.size(); j++) {
//
//        reviewId = reviews.get(j).getAttribute("aria-labelledby");
//        tweetID = tweetBodyPath.get(j).getAttribute("id");
//        reviewIdXPath = "//article[@data-testid=\"tweet\" and @aria-labelledby='"+reviewId+"']";
//
//
//        reviewComment=driver.findElement(By.xpath(reviewIdXPath + "//div[@lang=\"en\" and @id='"+tweetID+"']" )).getText(); //+"//div[@id=\"id__oypwvdnz1y\"]"
//        //*[@id="id__kn5i726qqja"]
//        // String review = reviews.get(j).getText();
//        System.out.println(reviewComment);
//        list.add(reviewComment);
//
//        try {
//        Thread.sleep(1000);
//        } catch (Exception e) {
//        }
//        if(reviews.size()==60){
//        break;
//        }
//        }
//        try{
//        Thread.sleep(1000);
//        }
//        catch(Exception e) {
//        }
//        i++;
//        }
//        FileWriter writer = new FileWriter("twitterRaw.txt");
//        for (String str : list) {
//        writer.write(str + System.lineSeparator() + System.lineSeparator() + System.lineSeparator());
//        }
//        writer.close();


//        List<WebElement> reviews = driver.findElements(By.xpath("//*[@data-testid='tweet']"));
//        for (int j = 1; j < reviews.size(); j++) {
//
//            String review = reviews.get(j).getText();
//            System.out.println(review);
//    list.add(review);
//
//            try {
//                Thread.sleep(1000);
//            } catch (Exception e) {
//            }
//            if(reviews.size()==60){
//                break;
//            }
//            }
//
//            FileWriter writer = new FileWriter("twitter1.txt");
//            for (String str : list) {
//                writer.write(str + System.lineSeparator() + System.lineSeparator() + System.lineSeparator());
//            }
//            writer.close();



//        List<WebElement> reviews = driver.findElements(By.xpath("//*[@data-testid='tweet']"));
//        for (int j = 1; j < reviews.size(); j++) {
//
//            String review = reviews.get(j).getText();
//            System.out.println(review);
            //    list.add(review);
//
//            try {
//                Thread.sleep(1000);
//            } catch (Exception e) {
//            }
//            if(reviews.size()==60){
//                break;
//            }
//            }
//
//            FileWriter writer = new FileWriter("twitter1.txt");
//            for (String str : list) {
//                writer.write(str + System.lineSeparator() + System.lineSeparator() + System.lineSeparator());
//            }
//            writer.close();




//
//package Selenium;// Generated by Selenium IDE
//        import io.github.bonigarcia.wdm.WebDriverManager;
//        import org.junit.Test;
//        import org.junit.Before;
//        import org.junit.After;
//        import org.openqa.selenium.By;
//        import org.openqa.selenium.WebDriver;
//        import org.openqa.selenium.chrome.ChromeDriver;
//        import org.openqa.selenium.Dimension;
//        import org.openqa.selenium.WebElement;
//        import org.openqa.selenium.JavascriptExecutor;
//        import java.io.FileWriter;
//        import java.io.IOException;
//        import java.util.*;
//        import java.util.concurrent.TimeUnit;
//
//public class TwitterReview {
//    private WebDriver driver;
//    private Map<String, Object> vars;
//    JavascriptExecutor js;
//    @Before
//    public void setUp() {
//        WebDriverManager.chromedriver().setup();
//        driver = new ChromeDriver();
//        js = (JavascriptExecutor) driver;
//        vars = new HashMap<String, Object>();
//    }
//    @After
//    public void tearDown() {
//        driver.quit();
//    }
//    @Test
//    public void example() throws IOException {
//
//        driver.get("https://twitter.com/search?q=hsbc&src=typed_query&f=top");
//        driver.manage().window().maximize();
//        driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
//        JavascriptExecutor js=(JavascriptExecutor)driver;
//        List<String> list = new ArrayList<>();
//        for(int i=1; i<10;i++)
//            js.executeScript("window.scrollBy(0,550)");
//
//        try{
//            Thread.sleep(2000);
//        }
//        catch(Exception e) {
//        }
//
//        List<WebElement> reviews = driver.findElements(By.xpath("//*[@data-testid='tweet']"));
//
//        for(int j = 1; j<reviews.size(); j++){
//
//
//
//            String review = reviews.get(j).getText();
//            System.out.println(review);
//            list.add(review);
//
//            driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);
//
//        }
//        FileWriter writer = new FileWriter("twitter1.txt");
//        for(String str: list) {
//            writer.write(str + System.lineSeparator() + System.lineSeparator() +System.lineSeparator());
//        }
//        writer.close();
//    }
//}
//
//