package Selenium;// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.interactions.Actions;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class TWITTER2 {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void example() throws IOException {
        Actions actions = new Actions(driver);

        String URL1 = "https://twitter.com/search?q=hsbc%20mobile%20banking&src=typed_query&f=live";
        driver.get(URL1);
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(1, TimeUnit.SECONDS);
        JavascriptExecutor js = (JavascriptExecutor) driver;
        List<String> list = new ArrayList<>();
        StringBuilder fileContent = new StringBuilder();
        List<String> usernameList = new ArrayList<>();
        List<String> tweetIDList = new ArrayList<>();
        List<WebElement> tweets = driver.findElements(By.xpath("//*[@data-testid='tweet']"));


        for (int i=0;i<tweets.size();i++) {
                String TweetID = tweets.get(i).getAttribute("aria-labelledby");

                tweetIDList.add(TweetID);
                 String tweetIdXPath = "//article[@data-testid=\"tweet\" and @aria-labelledby='"+TweetID+"']";
            System.out.println(TweetID);

            }
//            js.executeScript("window.scrollTo(0, document.body.scrollHeight)");
//            try {
//                Thread.sleep(3000);
//            } catch (Exception e) {
//            }


        }

//          for (WebElement tweetID : tweets) {
//        String tweetIDNo = tweetID.getAttribute("aria-labelledby");
//        System.out.println(tweetIDNo + System.lineSeparator());
//        tweetIDList.add(tweetIDNo);

//            for (int i = 0; i < tweets.size(); i++) {
//                String TweetID = tweets.get(i).getAttribute("aria-labelledby");
//                tweetIDList.add(TweetID);
//
//                //read TweetID
//                //if TweetID not in tweetIDList, extract info and add TweetID to tweetIDlist
//                //else, move on to next tweet
//                //when no more unique IDs available, scroll to load next set
//
//                String tweetXPath = "//article[@data-testid=\"tweet\" and @aria-labelledby='" + TweetID + "']";
//
//                String tweetBody1 = driver.findElement(By.xpath(tweetXPath + "//*[@class=\"css-901oao r-18jsvk2 r-37j5jr r-a023e6 r-16dba41 r-rjixqe r-bcqeeo r-bnwqim r-qvutc0\" and @dir=\"auto\"]")).getText();
//                String username = driver.findElement(By.xpath(tweetXPath + "//*[@class=\"css-901oao css-bfa6kz r-14j79pv r-18u37iz r-37j5jr r-a023e6 r-16dba41 r-rjixqe r-bcqeeo r-qvutc0\"]//span[@class = \"css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0\"]")).getText();
//
//                System.out.println(username);
//                System.out.println(tweetBody1);
//                fileContent = fileContent.append("\""+username+"\""+","+"\""+tweetBody1+"\"").append("\r\n");
//
//
//            }
//        File file = new File("tweets.csv");
//        try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
//            writer.write(fileContent.toString());
//        }

        }






//            for (WebElement tweets : tweetBody) {
//                String tweetBody1 = tweets.getText();
//                System.out.println(tweetBody1 + System.lineSeparator());
//                list.add(tweetBody1);
//            }
//
//
//            List<WebElement> username = driver.findElements(By.xpath("//*[@data-testid='tweet']//div[@class=\"css-901oao css-bfa6kz r-14j79pv r-18u37iz r-37j5jr r-a023e6 r-16dba41 r-rjixqe r-bcqeeo r-qvutc0\"]//span[@class = \"css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0\"]"));
//            for (WebElement usernameGrab : username) {
//                String usernameAdd = usernameGrab.getText();
//                System.out.println(usernameAdd + System.lineSeparator());
//                usernameList.add(usernameAdd);
//            }
//            js.executeScript("window.scrollTo(0, document.body.scrollHeight)");
//            try {
//                Thread.sleep(3000);
//            } catch (Exception e) {
//            }
//
//        }
//    }





//    @Test
//    public void example() throws IOException {
//
//        String URL1 = "https://twitter.com/search?q=hsbc%20mobile%20banking&src=typed_query&f=live";
//        driver.get(URL1);
//        driver.manage().window().maximize();
//        driver.manage().timeouts().implicitlyWait(1, TimeUnit.SECONDS);
//        JavascriptExecutor js = (JavascriptExecutor) driver;
//        List<String> list = new ArrayList<>();
//        List<String> usernameList = new ArrayList<>();
//        List<WebElement> tweetList = driver.findElements(By.xpath("//*[@data-testid='tweet']"));
//
//        for (int i = 0; i < 2; i++) {
//
//            List<WebElement> tweetBody = driver.findElements(By.xpath("//div[@lang=\"en\" and @dir=\"auto\"]"));
//            for (WebElement tweets : tweetBody) {
//                String tweetBody1 = tweets.getText();
//                System.out.println(tweetBody1 + System.lineSeparator());
//                list.add(tweetBody1);
//            }
//
//
//            List<WebElement> username = driver.findElements(By.xpath("//*[@data-testid='tweet']//div[@class=\"css-901oao css-bfa6kz r-14j79pv r-18u37iz r-37j5jr r-a023e6 r-16dba41 r-rjixqe r-bcqeeo r-qvutc0\"]//span[@class = \"css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0\"]"));
//            for (WebElement usernameGrab : username) {
//                String usernameAdd = usernameGrab.getText();
//                System.out.println(usernameAdd + System.lineSeparator());
//                usernameList.add(usernameAdd);
//            }
//            js.executeScript("window.scrollTo(0, document.body.scrollHeight)");
//            try {
//                Thread.sleep(3000);
//            } catch (Exception e) {
//            }
//
//        }
//    }
//
//
//}